language: node_js
sudo: false
node_js:
  - '5.4.1'
install:
  - ./scripts/ci-lite/install.sh
script:
  - ./scripts/ci-lite/build.sh && ./scripts/ci-lite/test.sh
after_script:
  - ./scripts/ci-lite/cleanup.sh