dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
os:
  - linux
branches:
  only:
  - master
env:
  global:
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
  matrix:
    - SCRIPT="run-e2e-tests --fast"
before_install:
  - npm install -g gulp --no-optional
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install --no-optional
  - gulp add-example-boilerplate
script:
  - gulp $SCRIPT